name: CFP_calendar_nightly
on:
  push:
    branches:
      - main
  schedule:
    - cron: '01 0 * * *'


env:
  CI_COMMIT_MESSAGE: Nightly CFP Calendar Build
  CI_COMMIT_AUTHOR: CFP Calendar Bot


jobs:
  build_icalendar:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the latest code
        uses: actions/checkout@v3

      - name: Install requirements.txt
        run: pip install -r requirements.txt

      - name: Create iCalendar
        run: python main.py

      - name: Check modified iCalendar
        id: icalendar_check
        run: .github/icalendar_check.sh

      - name: Commit and push iCalendar
        if: steps.icalendar_check.outputs.assets_changed == 'true'
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "cfp_calendar@users.noreply.github.com"
          git add assets
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push

# Inspired by -> https://joht.github.io/johtizen/build/2022/01/20/github-actions-push-into-repository.html